### ISSUE TITLE
CONTACT ME

### ISSUE THREAD

**Issue by ManuCiao10** [Locusc/dewu-api#4]
Hello, how did you find out how the sign was generated?

**Comment by Tohtanbek** [comment]
Hi, do you have it working?
I'm trying to run it but getting 500 error

**Comment by ManuCiao10** [comment]
> Hi, do you have it working? I'm trying to run it but getting 500 error

hi, the script to generate the sign has been changed.

**Comment by Tohtanbek** [comment]
oh, thank you for info
Have a nice day
